# -*- coding: utf-8 -*-
"""exploratory_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4QDtClm1Qu8UJs6mO7OkSFyopALI-ba
"""

import pypdf
import pandas as pd
import matplotlib.pyplot as plt
import re
from collections import Counter

# Define local file paths
files = {
    "ML-AI (Nilsson)": "MLBOOK.pdf",
    "Healthcare (WHO)" : "dsa664.pdf"
}
def analyze_corpus(name, path):
  print(f"Analyzing {name}...")
  reader = pypdf.PdfReader(path)
  num_pages = len(reader.pages)

  full_text = ""
  for page in reader.pages:
    full_text += page.extract_text() or ""

  # 1. MATH DENSITY CALCULATION
  # Counts LaTeX-style symbols and common operators
  math_patterns = r'[\$\\\sum\\frac\\alpha\\beta\\theta\\int\\partial\=\+\-\*\/]'
  math_symbols = len(re.findall(math_patterns, full_text))

  # 2. LINGUISTIC CALCULATION
  words = re.findall(r'\w+', full_text.lower())
  word_count = len(words)

  # 3. PROCEDURAL LOGIC (BULLETS/IF-THEN)
  # Looks for diagnostic flow indicators and list structures
  procedural_terms = len(re.findall(r'\b(if|then|else|threshold|criteria|step|stage)\b', full_text, re.I))
  bullets = len(re.findall(r'^\s*[\u2022\u25cf\u25cb\u25aa\u25ab\*\-]\s', full_text, re.M))

  return{
      "Domain": name,
      "Pages": num_pages,
      "Word Count": word_count,
      "Math Density (per page)": round(math_symbols / num_pages, 2),
      "Logic/List Density (per page)": round((procedural_terms + bullets) / num_pages, 2)
  }
# Run the analysis
eda_data = []
for name, path in files.items():
  try:
    eda_data.append(analyze_corpus(name, path))
  except Exception as e:
    print(f"Could not find {path}. Error: {e}")
# 4. RESULTS & VALIDATION
if eda_data:
  df = pd.DataFrame(eda_data)
  print("\n--- CALCULATED EDA METRICS ---")
  print(df)

